name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: input
    id: version
    attributes:
      label: Host Version
      description: Run `pseudocoder --version`
      placeholder: v0.1.0-alpha.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux
        - WSL
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: macOS 14.2, Ubuntu 22.04, etc.
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: Network Setup
      options:
        - Tailscale
        - LAN (same network)
        - Other
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - Connection / Pairing
        - Terminal
        - Review Cards
        - Commit / Push
        - Sessions
        - Mobile App UI
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Start host with `pseudocoder start --pair --qr`
        2. Connect from phone
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Any relevant output, error messages, or screenshots
    validations:
      required: false
