name: Feature Request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Pseudocoder better? We'd love to hear it.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Terminal
        - Review Cards
        - Sessions
        - Mobile App UI
        - Host CLI
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
